[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
build_flags =
    -DEMBODIED_ARM_UART_BAUD=115200
